
server:
  port: 8023
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumerA
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    #虚拟host 可以不设置,使用server默认host
    virtual-host: test01





queue:
  direct:
    name: TestDirectQueue

exchange:
  direct:
    name: TestDirectExchange
    lonely: lonelyDirectExchange

route:
  direct:
    key: TestDirectRouting

