server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-providerA
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    #虚拟host 可以不设置,使用server默认host
    virtual-host: test01

    # 消息确认配置项

    # 确认消息已发送到交换机（Exchange）
    publisher-confirm-type: correlated
    # 确认消息已发送到队列（Queue）
    publisher-returns: true

queue:
  direct:
    name: TestDirectQueue

exchange:
  direct:
    name: TestDirectExchange
    lonely: lonelyDirectExchange

route:
  direct:
    key: TestDirectRouting

